src/Entity/Room.php
<?php

namespace App\Entity;

use App\Repository\RoomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=RoomRepository::class)
 */
class Room
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("rooms")
     * @MaxDepth(2)
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Regex(
     *     pattern="/^[1-4]+$/",
     *     message="maximum number of people in the room between 1 and 4"
     * )
     * @Groups("rooms")
     */
    private $nb_personnes;

    /**
     * @ORM\Column(type="text")
     * @Groups("rooms")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("rooms")
     */
    private $type;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThanOrEqual(
     *     value=0,
     *     message="price must be positive"
     * )
     * @Groups("rooms")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity=Hotel::class, inversedBy="rooms")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idHotel;

    /**
     * @ORM\OneToMany(targetEntity=Options::class, mappedBy="room_id", orphanRemoval=true)
     *
     */
    public $options;

    private $id2;

    /**
     * @ORM\OneToMany(targetEntity=ReservationHotel::class, mappedBy="roomId", orphanRemoval=true)
     */
    private $reservationHotels;

    public function __toString()
    {
        return (string)$this->getId();
    }

    public function __construct()
    {
        $this->options = new ArrayCollection();
        $this->options_id = new ArrayCollection();
        $this->reservationHotels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function getId2(): ?string
    {
        return $this->id;
    }

    public function getNbPersonnes(): ?int
    {
        return $this->nb_personnes;
    }

    public function setNbPersonnes(int $nb_personnes): self
    {
        $this->nb_personnes = $nb_personnes;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }


    public function getIdHotel(): ?hotel
    {
        return $this->idHotel;
    }

    public function setIdHotel(?Hotel $idHotel): self
    {
        $this->idHotel = $idHotel;

        return $this;
    }


    /**
     * @return Collection|Options[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Options $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->setRoomId($this);
        }

        return $this;
    }

    public function removeOption(Options $option): self
    {
        if ($this->options->removeElement($option)) {
            // set the owning side to null (unless already changed)
            if ($option->getRoomId() === $this) {
                $option->setRoomId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ReservationHotel[]
     */
    public function getReservationHotels(): Collection
    {
        return $this->reservationHotels;
    }

    public function addReservationHotel(ReservationHotel $reservationHotel): self
    {
        if (!$this->reservationHotels->contains($reservationHotel)) {
            $this->reservationHotels[] = $reservationHotel;
            $reservationHotel->setRoomId($this);
        }

        return $this;
    }

    public function removeReservationHotel(ReservationHotel $reservationHotel): self
    {
        if ($this->reservationHotels->removeElement($reservationHotel)) {
            // set the owning side to null (unless already changed)
            if ($reservationHotel->getRoomId() === $this) {
                $reservationHotel->setRoomId(null);
            }
        }

        return $this;
    }


}

src/Form/RoomType.php
<?php

namespace App\Form;

use App\Entity\Options;
use App\Entity\Room;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RoomType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nb_personnes')
            ->add('description')
            ->add('type')
            ->add('prix')
            ->add('idHotel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Room::class,
        ]);
    }
}

src/Controller/RoomController.php
<?php

namespace App\Controller;

use App\Entity\Room;
use App\Entity\Options;
use App\Form\RoomType;
use App\Repository\OptionsRepository;
use App\Repository\RoomRepository;
use Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter;
use Omines\DataTablesBundle\Column\TextColumn;
use Omines\DataTablesBundle\DataTableFactory;
use phpDocumentor\Reflection\DocBlock\Description;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

/**
 * @Route("/room")
 */
class RoomController extends AbstractController
{
    /**
     * @Route("/", name="room_index", methods={"GET"})
     */
    public function index(Request $request, DataTableFactory $dataTableFactory,RoomRepository $roomRepository,OptionsRepository $optionsRepository): Response
    {
        $table = $dataTableFactory->create()

            ->add('nb_personnes', TextColumn::class, ['label' => 'nb_personnes', 'orderable'=> true,])
            ->add('description', TextColumn::class, ['label' => 'description', 'orderable'=> true,])
            ->add('type', TextColumn::class, ['label' => 'type', 'orderable'=> true,])
            ->add('prix', TextColumn::class, ['label' => 'prix', 'orderable'=> true,])
            ->add('idHotel', TextColumn::class, ['label' => 'HOTEL', 'orderable'=> true, 'field' => 'idHotel.name','searchable'=>true,])
            ->add('option', TextColumn::class, ['label' => 'options', 'orderable'=> false, 'render' => function($value ,$context) {
                $name = $context->getId();

                $user = $this->getDoctrine()
                    ->getRepository(Options::class)
                    ->findBy(['room_id' => $name]);

                $comma_separated = implode(",", $user);
                if ($user==null)
                return null;
                    else
                        return $comma_separated;
            }])
            ->add('id', TextColumn::class, ['orderable'=> false,'label' => 'ACTION','searchable'=>false,'render' => function($value, $context) {
                return sprintf('<a href="%u">SHOW</a> <a href="%d/edit">EDIT</a>', $value,$value);
            }])
            ->createAdapter(ORMAdapter::class, [
                'entity' => Room::class,
            ])
            ->handleRequest($request);

        if ($table->isCallback()) {
            return $table->getResponse();
        }

        return $this->render('Room/index.html.twig', [
            'datatable5' => $table,
            'gallery' => $roomRepository->findAll(),

        ]);
    }

    /**
     * @Route("/new", name="room_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $room = new Room();
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($room);
            $entityManager->flush();

            return $this->redirectToRoute('room_index');
        }

        return $this->render('room/new.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_show", methods={"GET"},requirements={"id"="\d+"})
     */
    public function show(Room $room): Response
    {
        return $this->render('room/show.html.twig', [
            'room' => $room,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="room_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Room $room): Response
    {
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('room_index');
        }

        return $this->render('room/edit.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Room $room): Response
    {
        if ($this->isCsrfTokenValid('delete'.$room->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($room);
            $entityManager->flush();
        }

        return $this->redirectToRoute('room_index');
    }

    /**
     * @Route("/searchRoomx",name="searchRoomx")
     */
    public function searchRoomx(Request $request,NormalizerInterface $Normalizer)
    {
        $repository = $this->getDoctrine()->getRepository(Room::class);
        $requestString=$request->get('searchValue');
        $Rooms= $repository->findRoomByDescription($requestString);



        $jsonContent = $Normalizer->normalize($Rooms, 'html',['groups'=>'post:rooms']);

        $retour=json_encode($jsonContent,JSON_FORCE_OBJECT);

       // dd($retour);
       // echo json_last_error_msg();
        return new Response($retour);

    }
}

templates/room/_delete_form.html.twig
<script src="https://www.google.com/recaptcha/api.js" async defer></script>


<div class="form_container">
    <form  method="post" action="{{ path('room_delete', {'id': room.id}) }}" id="my_captcha_form">
        <div class="g-recaptcha"
             data-sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
        ></div>
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ room.id) }}">
        <button class="btn-outline-primary" >Delete</button>
    </form>
</div>


<script>


    document.getElementById("my_captcha_form").addEventListener("submit",function(evt)
    {

        var response = grecaptcha.getResponse();
        if(response.length == 0)
        {
            //reCaptcha not verified
            alert("please verify you are humann!");
            evt.preventDefault();
            return false;
        }
        //captcha verified
        //do the rest of your validations here

    });
</script>

templates/room/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Room{% endblock %}

{% block body %}
<h4 class="widget-header">Edit Room</h4>
<div class="col-lg-6 col-12 mx-auto">
    {{ include('room/_form.html.twig', {'button_label': 'Update'}) }}
</div>
    <a href="{{ path('room_index') }}">back to list</a>

    {{ include('room/_delete_form.html.twig') }}
{% endblock %}

templates/room/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Galleries test{% endblock %}


{% block body %}
    <h4>Rooms</h4>
    <!-- in the <head> section -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.2.1/dt-1.10.16/datatables.min.css"/>
    <!-- before the closing <body> tag -->
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.2.1/dt-1.10.16/datatables.min.js"></script>
    <!-- Insert this where you want the table to appear -->
    <div class="table table-bordered table-hover table-striped mb-4" id="presidents5">Loading...</div>
    <a class="btn-outline-primary" href="{{ path('room_new') }}">ADD NEW</a>







    <!-- Insert this at the end of your body element, but before the closing tag -->
    <script src="{{ asset('bundles/datatables/js/datatables.js') }}"></script>
    <script>
        $(function() {
            $('#presidents5').initDataTables({{ datatable_settings(datatable5) }}, { searching: true,});

        });




    </script>


{% endblock %}

templates/room/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Room{% endblock %}

{% block body %}
    <h1>Create new Room</h1>

    {{ include('room/_form.html.twig') }}

    <a href="{{ path('room_index') }}">back to list</a>
{% endblock %}

templates/room/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Room{% endblock %}

{% block body %}
    <h1>Room</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ room.id }}</td>
            </tr>
            <tr>
                <th>Nb_personnes</th>
                <td>{{ room.nbPersonnes }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ room.description }}</td>
            </tr>

            <tr>
                <th>Type</th>
                <td>{{ room.type }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ room.prix }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('room_index') }}">back to list</a>

    <a href="{{ path('room_edit', {'id': room.id}) }}">edit</a>

    {{ include('room/_delete_form.html.twig') }}
{% endblock %}